### ISSUE TITLE
Creating reporting module inside utils. 

### ISSUE THREAD

**Issue by canaleal** [canaleal/Python-Banking-DataProcessor#1]
Reporting module should create a simple csv calculating the following:

1. Total Balance
2. Total withdrawals
3. Total deposits
4. Info
5. Summary
6. Description

Output should be in csv or excel.

**Comment by flamesjames** [comment]
Hey there @canaleal! I'd like to take this issue up. Can you please assign it to me?

**Comment by canaleal** [comment]
Sure thing @flamesjames .

**Comment by flamesjames** [comment]
@canaleal thank you!

**Comment by flamesjames** [comment]
Hello @canaleal! I began development on this today and just had a couple of clarifications to run by you to make sure the end product meets your expectations:

1.  Where should this script be pulling the transaction info from? Shall I just build a list of temp transactions to be used or do you have somewhere specific you will pull the data from?
2. Do you have an example of what you want the output data to look like (i.e. summary, description, etc.)?

Please let me know if there's anything else that would be required. Thanks!

**Comment by canaleal** [comment]
Hey there, 

1. I've merged some temp data from Kaggle containing 116201 rows of data and 7 columns into main. If you'd also like to create your own temp data then that would be okay. 

2. For the time being a simple csv file containing the results of the cleaned up data using pandas describe(). The summary is a general overview for when the data was processed, how much data was removed due to missing/ corrupted inputs, largest/smallest values for withdrawals and deposits (Describe covers this too). If you'd like to make some other additions, feel free to do so. 

No other requirements.

**Comment by flamesjames** [comment]
Hey @canaleal - I'm not sure I understand this statement: "how much data was removed due to missing/ corrupted inputs", can you elaborate how the data should be "cleaned"?

I understood your initial issue description as taking in a list of transactions and then outputting the columns you provided based on the full data set. Should the list of input transactions be modified during this process or something? The more details of what you're expecting (and the use case) the better.

**Comment by canaleal** [comment]
For missing data, there are 116000 rows of data, but Im not sure if all of them have a withdrawal or deposit amount. If a row has neither a withdrawal or deposit amount, then it can be removed. 

1. Load the data from the CSV
2. Check if each row has a withdrawal or deposit amount
3. Remove rows that don't have either
4. The value date and date columns are the same so you could remove the value date column.
5. Check if there are any duplicate rows.
6. Remove all the duplicate rows. 
7. Print describe and save the outcome to a csv
8. Print the summary and save the outcome to a csv
9. End

**Comment by flamesjames** [comment]
@canaleal - Perfect! Thanks a lot Alex. It makes much more sense now. Let me work on getting a working copy of the script and then will review it with you to see if you'd like any modifications made before merging.

**Comment by flamesjames** [comment]
Hey @canaleal - I am very close on completing the script, I should be able to wrap it up tonight for a review..

One question I had while working is what I should be doing with the "total balance" column -- would I just need to print the value in the "Total Balance" column of the very last row (final balance after all other transactions)? Or am I thinking about this incorrectly?

**Comment by canaleal** [comment]
You are correct. Just need to print the "Total Balance"

**Comment by flamesjames** [comment]
Hey @canaleal - Added reporting module with 7f45a9fd41d70fc681a1bf22034fe0ce435a5994. Please let me know if any modifications are needed before the final merge. Thanks!

**Comment by canaleal** [comment]
@flamesjames  Sorry, I've been busy with work. All of it looks good, I've already merged it. Closing this issue now.

**Comment by flamesjames** [comment]
> @flamesjames  Sorry, I've been busy with work. All of it looks good, I've already merged it. Closing this issue now. 
> 
> 

No issues at all @canaleal - happy to help out! Thanks
