### ISSUE TITLE
Small Readme Issue

### ISSUE THREAD

**Issue by flamesjames** [canaleal/Python-Banking-DataProcessor#2]
I believe the wrong command is used in `lines 71` and`83` of the `README.md`. Here is the following change that should be made:
```diff
- pip install requirements.txt
+ pip install -r requirements.txt
```

I am willing to make this change for you if you'd like to assign it to me, only if you agree with the changes.

**Comment by canaleal** [comment]
Nice find, and sure, I'll assign it to you.
